const cardStat = [
  ['Action (set A)', 'Action (set B)', 'Action (set C)', 'Adjective', 'Animal (set A)', 'Animal (set B)', 'Clothes', 'Emotions'],
  [
    {
      word: 'cry',
      translation: 'плакать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'dance',
      translation: 'танцевать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'dive',
      translation: 'нырять',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'draw',
      translation: 'рисовать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'fish',
      translation: 'ловить рыбу',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'fly',
      translation: 'летать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'hug',
      translation: 'обнимать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'jump',
      translation: 'прыгать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'open',
      translation: 'открывать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'play',
      translation: 'играть',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'point',
      translation: 'указывать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'ride',
      translation: 'ездить',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'run',
      translation: 'бегать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'sing',
      translation: 'петь',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'skip',
      translation: 'пропускать, прыгать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'swim',
      translation: 'плавать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'argue',
      translation: 'спорить',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'build',
      translation: 'строить',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'carry',
      translation: 'нести',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'catch',
      translation: 'ловить',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'drive',
      translation: 'водить машину',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'drop',
      translation: 'падать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'pull',
      translation: 'тянуть',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'push',
      translation: 'толкать',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'big',
      translation: 'большой',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'small',
      translation: 'маленький',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'fast',
      translation: 'быстрый',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'slow',
      translation: 'медленный',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'friendly',
      translation: 'дружелюбный',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'unfriendly',
      translation: 'недружелюбный',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'young',
      translation: 'молодой',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'old',
      translation: 'старый',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'cat',
      translation: 'кот',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'chick',
      translation: 'цыплёнок',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'chicken',
      translation: 'курица',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'dog',
      translation: 'собака',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'horse',
      translation: 'лошадь',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'pig',
      translation: 'свинья',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'rabbit',
      translation: 'кролик',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'sheep',
      translation: 'овца',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'bird',
      translation: 'птица',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'fish',
      translation: 'рыба',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'frog',
      translation: 'жаба',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'giraffe',
      translation: 'жирафа',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'lion',
      translation: 'лев',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'mouse',
      translation: 'мышь',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'turtle',
      translation: 'черепаха',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'dolphin',
      translation: 'дельфин',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'skirt',
      translation: 'юбка',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'pants',
      translation: 'брюки',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'blouse',
      translation: 'блузка',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'dress',
      translation: 'платье',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'boot',
      translation: 'ботинок',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'shirt',
      translation: 'рубашка',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'coat',
      translation: 'пальто',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'shoe',
      translation: 'туфли',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
  [
    {
      word: 'sad',
      translation: 'грустный',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'angry',
      translation: 'сердитый',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'happy',
      translation: 'счастливый',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'tired',
      translation: 'уставший',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'surprised',
      translation: 'удивлённый',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'scared',
      translation: 'испуганный',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'smile',
      translation: 'улыбка',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
    {
      word: 'laugh',
      translation: 'смех',
      trainCount: 0,
      playRight: 0,
      playWrong: 0,
    },
  ],
];

export default cardStat;
